### PR TITLE
Fixes for #3

### PR DESCRIPTION
**Pull request by srph**

### CODE REVIEW

**Comment by srph** [comment]
I can handle this.

I'm not sure what https://github.com/richardkeep/validate/commit/4e480fbfe4bd7b23a9256dcfb585d495995e2c55 does, but we need to undo its changes.

**Comment by richardkeep** [comment]
you can undo the changes

**Comment by srph** [comment]
Done!

Anyway, it seems that you deleted the contents of `app.js` in https://github.com/richardkeep/validate/commit/4e480fbfe4bd7b23a9256dcfb585d495995e2c55.

**Comment by richardkeep** [comment]
Yeah, I deleted the previous contents.

**Comment by srph** [comment]
Thanks!

**Comment by richardkeep** [comment]
I'm learning a lot. Thanks

**Pull request merged**
